#mytextsample1 = "My first name is {} My middle name is {} My last name is {}. {} "
#mytextsample2 = mytextsample1.format ("Kyle John", "Gumapit", "Jumalon", "—Thank You! ")
#print(mytextsample2)



#samplepy1 = "My hobby is {0}, My favorite exercise is {1}, My goal in life is to become a {3}, I am a {2}"
#samplepy2 = samplepy1.format ("playing mobile legends", "Calisthenics", "talented person and soft hearted with a caring person", "good students and academic achiever")
#print(samplepy2)



#mytextsample3 = "Hi! my name is {name}, I like to play {sports},  My strenght in life are my {person}, The thing that I don't like the most is {Thing}"
#Mytextsample3 = mytextsample3. format(name="Kyle John Jumalon", sports="calisthenics exercise", person="family", Thing="bolo knife")
#print(Mytextsample3)



#Item = "pull up bar" 
#Cost = 115.9
#Mysampletext4 = "The item is %s it cost with %.2f" % (Item, Cost)
#print(Mysampletext4)



Exam = "midterm" 
Tuition = 2557
MySampletext5 = f"The upcoming {Exam} has a total of {Tuition * 10) pesos."
print(MySampletext5)
